In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
df=pd.read_csv('German Credit Dataset.csv')
df

,checking_balance,months_loan_duration,credit_history,purpose,amount,savings_balance,employment_duration,percent_of_income,years_at_residence,age,other_credit,housing,existing_loans_count,job,dependents,phone,default
0,< 0 DM,6,critical,furniture/appliances,1169,unknown,> 7 years,4,4,67,none,own,2,skilled,1,yes,no
1,1 - 200 DM,48,good,furniture/appliances,5951,< 100 DM,1 - 4 years,2,2,22,none,own,1,skilled,1,no,yes
2,unknown,12,critical,education,2096,< 100 DM,4 - 7 years,2,3,49,none,own,1,unskilled,2,no,no
3,< 0 DM,42,good,furniture/appliances,7882,< 100 DM,4 - 7 years,2,4,45,none,other,1,skilled,2,no,no
4,< 0 DM,24,poor,car,4870,< 100 DM,1 - 4 years,3,4,53,none,other,2,skilled,2,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,unknown,12,good,furniture/appliances,1736,< 100 DM,4 - 7 years,3,4,31,none,own,1,unskilled,1,no,no
996,< 0 DM,30,good,car,3857,< 100 DM,1 - 4 years,4,4,40,none,own,1,management,1,yes,no
997,unknown,12,good,furniture/appliances,804,< 100 DM,> 7 years,4,4,38,none,own,1,skilled,1,no,no
998,< 0 DM,45,good,furniture/appliances,1845,< 100 DM,1 - 4 years,4,4,23,none,other,1,skilled,1,yes,yes
999,1 - 200 DM,45,critical,car,4576,100 - 500 DM,unemployed,3,4,27,none,own,1,skilled,1,no,no

In [3]:
df.duplicated().sum()

np.int64(0)

In [4]:
df.isna().sum()

checking_balance        0
months_loan_duration    0
credit_history          0
purpose                 0
amount                  0
savings_balance         0
employment_duration     0
percent_of_income       0
years_at_residence      0
age                     0
other_credit            0
housing                 0
existing_loans_count    0
job                     0
dependents              0
phone                   0
default                 0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   checking_balance      1000 non-null   object
 1   months_loan_duration  1000 non-null   int64
 2   credit_history        1000 non-null   object
 3   purpose               1000 non-null   object
 4   amount                1000 non-null   int64
 5   savings_balance       1000 non-null   object
 6   employment_duration   1000 non-null   object
 7   percent_of_income     1000 non-null   int64
 8   years_at_residence    1000 non-null   int64
 9   age                   1000 non-null   int64
 10  other_credit          1000 non-null   object
 11  housing               1000 non-null   object
 12  existing_loans_count  1000 non-null   int64
 13  job                   1000 non-null   object
 14  dependents            1000 non-null   int64
 15  phone                 1000 non-null   object
 16  default               1000 non-null   object
dtypes: int64(7), object(10)
memory usage: 132.9+ KB

In [8]:
for i in df.columns:
    if df[i].dtype=='object':
        df[i]=df[i].astype('category')
        df[i]=df[i].cat.codes

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   checking_balance      1000 non-null   int8
 1   months_loan_duration  1000 non-null   int64
 2   credit_history        1000 non-null   int8
 3   purpose               1000 non-null   int8
 4   amount                1000 non-null   int64
 5   savings_balance       1000 non-null   int8
 6   employment_duration   1000 non-null   int8
 7   percent_of_income     1000 non-null   int64
 8   years_at_residence    1000 non-null   int64
 9   age                   1000 non-null   int64
 10  other_credit          1000 non-null   int8
 11  housing               1000 non-null   int8
 12  existing_loans_count  1000 non-null   int64
 13  job                   1000 non-null   int8
 14  dependents            1000 non-null   int64
 15  phone                 1000 non-null   int8
 16  default               1000 non-null   int8
dtypes: int64(7), int8(10)
memory usage: 64.6 KB

In [10]:
df

,checking_balance,months_loan_duration,credit_history,purpose,amount,savings_balance,employment_duration,percent_of_income,years_at_residence,age,other_credit,housing,existing_loans_count,job,dependents,phone,default
0,1,6,0,4,1169,4,3,4,4,67,1,1,2,1,1,1,0
1,0,48,1,4,5951,2,0,2,2,22,1,1,1,1,1,0,1
2,3,12,0,3,2096,2,1,2,3,49,1,1,1,3,2,0,0
3,1,42,1,4,7882,2,1,2,4,45,1,0,1,1,2,0,0
4,1,24,3,1,4870,2,0,3,4,53,1,0,2,1,2,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,3,12,1,4,1736,2,1,3,4,31,1,1,1,3,1,0,0
996,1,30,1,1,3857,2,0,4,4,40,1,1,1,0,1,1,0
997,3,12,1,4,804,2,3,4,4,38,1,1,1,1,1,0,0
998,1,45,1,4,1845,2,0,4,4,23,1,0,1,1,1,1,1
999,0,45,0,1,4576,0,4,3,4,27,1,1,1,1,1,0,0

In [11]:
df.describe()

,checking_balance,months_loan_duration,credit_history,purpose,amount,savings_balance,employment_duration,percent_of_income,years_at_residence,age,other_credit,housing,existing_loans_count,job,dependents,phone,default
count,1000.000000,1000.000000,1000.00000,1000.000000,1000.000000,1000.0000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,1.582000,20.903000,1.07000,2.540000,3271.258000,2.1450,1.525000,2.973000,2.845000,35.546000,0.908000,1.071000,1.407000,1.274000,1.155000,0.404000,0.300000
std,1.253334,12.058814,1.05935,1.607789,2822.736876,1.1114,1.344315,1.118715,1.103718,11.375469,0.421561,0.531264,0.577654,0.946478,0.362086,0.490943,0.458487
min,0.000000,4.000000,0.00000,0.000000,250.000000,0.0000,0.000000,1.000000,1.000000,19.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000
25%,0.000000,12.000000,0.00000,1.000000,1365.500000,2.0000,0.000000,2.000000,2.000000,27.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000
50%,1.000000,18.000000,1.00000,3.000000,2319.500000,2.0000,1.000000,3.000000,3.000000,33.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000
75%,3.000000,24.000000,1.00000,4.000000,3972.250000,2.0000,3.000000,4.000000,4.000000,42.000000,1.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000
max,3.000000,72.000000,4.00000,5.000000,18424.000000,4.0000,4.000000,4.000000,4.000000,75.000000,2.000000,2.000000,4.000000,3.000000,2.000000,1.000000,1.000000

In [13]:
X=df.drop('default',axis=1)
Y=df['default']

In [14]:
X

,checking_balance,months_loan_duration,credit_history,purpose,amount,savings_balance,employment_duration,percent_of_income,years_at_residence,age,other_credit,housing,existing_loans_count,job,dependents,phone
0,1,6,0,4,1169,4,3,4,4,67,1,1,2,1,1,1
1,0,48,1,4,5951,2,0,2,2,22,1,1,1,1,1,0
2,3,12,0,3,2096,2,1,2,3,49,1,1,1,3,2,0
3,1,42,1,4,7882,2,1,2,4,45,1,0,1,1,2,0
4,1,24,3,1,4870,2,0,3,4,53,1,0,2,1,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,3,12,1,4,1736,2,1,3,4,31,1,1,1,3,1,0
996,1,30,1,1,3857,2,0,4,4,40,1,1,1,0,1,1
997,3,12,1,4,804,2,3,4,4,38,1,1,1,1,1,0
998,1,45,1,4,1845,2,0,4,4,23,1,0,1,1,1,1
999,0,45,0,1,4576,0,4,3,4,27,1,1,1,1,1,0

## Decison Tree with criterion='gini'

In [37]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier(criterion='gini',min_samples_split=30,min_samples_leaf=10)

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,Y,test_size=0.2,stratify=Y)

In [39]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier(min_samples_leaf=10, min_samples_split=30)

In [40]:
y_pred_train=dtree.predict(X_train)
y_pred_test=dtree.predict(X_test)

In [41]:
from sklearn.metrics import classification_report, accuracy_score
print('classification_report test',classification_report(y_test,y_pred_test))
print('classification_report train',classification_report(y_train,y_pred_train))

classification_report test               precision    recall  f1-score   support

           0       0.79      0.80      0.80       140
           1       0.53      0.52      0.52        60

    accuracy                           0.71       200
   macro avg       0.66      0.66      0.66       200
weighted avg       0.71      0.71      0.71       200

classification_report train               precision    recall  f1-score   support

           0       0.82      0.91      0.86       560
           1       0.71      0.52      0.60       240

    accuracy                           0.79       800
   macro avg       0.76      0.71      0.73       800
weighted avg       0.78      0.79      0.78       800

## Descion Tree with criterion='entropy'

In [42]:
dtree=DecisionTreeClassifier(criterion='entropy',min_samples_split=30,min_samples_leaf=10,max_depth=7)
dtree.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=7, min_samples_leaf=10,
                       min_samples_split=30)

In [43]:
y_pred_train=dtree.predict(X_train)
y_pred_test=dtree.predict(X_test)
from sklearn.metrics import classification_report, accuracy_score
print('classification_report test',classification_report(y_test,y_pred_test))
print('classification_report train',classification_report(y_train,y_pred_train))

classification_report test               precision    recall  f1-score   support

           0       0.81      0.82      0.82       140
           1       0.57      0.55      0.56        60

    accuracy                           0.74       200
   macro avg       0.69      0.69      0.69       200
weighted avg       0.74      0.74      0.74       200

classification_report train               precision    recall  f1-score   support

           0       0.82      0.91      0.86       560
           1       0.71      0.54      0.61       240

    accuracy                           0.80       800
   macro avg       0.77      0.72      0.74       800
weighted avg       0.79      0.80      0.79       800

## Feature importance in ensemble models and tree

In [52]:
dtree.feature_importances_.round(4)

array([0.3208, 0.1162, 0.0767, 0.0349, 0.1359, 0.0805, 0.0346, 0.0383,
       0.0119, 0.0636, 0.0366, 0.0124, 0.0176, 0.0199, 0.    , 0.    ])

In [53]:
X_train.columns

Index(['checking_balance', 'months_loan_duration', 'credit_history', 'purpose',
       'amount', 'savings_balance', 'employment_duration', 'percent_of_income',
       'years_at_residence', 'age', 'other_credit', 'housing',
       'existing_loans_count', 'job', 'dependents', 'phone'],
      dtype='object')

In [69]:
from sklearn.model_selection import cross_val_score
cv=cross_val_score(dtree,X_train,y_train,cv=5)

In [70]:
cv.mean()

np.float64(0.7112499999999999)

### Pruning: Deleting the less important feauters like 0,0199 ......

### Random Forest is used instead of DT

In [87]:
from sklearn.ensemble import RandomForestClassifier
rft=RandomForestClassifier(criterion='entropy',max_depth=6,min_samples_leaf=30)
rft.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=6, min_samples_leaf=30)

In [88]:
y_pred_rft_train=rft.predict(X_train)
y_pred_rft_test=rft.predict(X_test)
from sklearn.metrics import classification_report, accuracy_score
print('classification_report test',accuracy_score(y_test,y_pred_rft_test))
print('classification_report train',accuracy_score(y_train,y_pred_rft_train))

classification_report test 0.735
classification_report train 0.745